spring:
    application:
        name: chatapp-api
    datasource:
        url: jdbc:mysql://localhost:3307/chatapp
        username: root
        password: root
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    data:
        mongodb:
            uri: mongodb://root:root@localhost:27018/chatapp?authSource=admin
    mail:
        host: smtp.gmail.com
        username: nthtpk7h7i@gmail.com
        password: ${MAIL_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                    auth: true

jwt:
    signerKey: ${SIGNER_KEY}
    valid-duration: 3600
    refreshable-duration: 360000

outbound:
  chatapp:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"